### ISSUE TITLE
No Override menu

### ISSUE THREAD

**Issue by agassparkle** [krbz999/foundryvtt-items-with-spells-5e#14] opened 2023-12-01 14:37 UTC
Clicking the edit spell in the item opens the spell description, not the override menu. I tried without any addon, just Items with spells. Still the same.
Dnd 5e v2.4.0
Foundry v11.308

**Comment by krbz999** [comment] 2023-12-01 17:13
Is this a duplicate of #5?

**Comment by agassparkle** [comment] 2023-12-01 17:46
Yes it is. Thank you

**Closed as not planned** 2023-12-01 17:51 UTC
Labels: wontfix
