### ISSUE TITLE
Need Update for DnD 5e 3.1.2

### ISSUE THREAD

**Issue by Morepheous** [krbz999/foundryvtt-items-with-spells-5e#29] opened 2024-04-11 21:42 UTC
Maximum system version is set to 2.4.9 so cannot active maodule. Not sure how to manually remove this requirement(like you can with when a maxium version of Foundry is set)

**Comment by krbz999** [comment] 2024-04-11 21:45
No such plans, sorry.

Closing this as a duplicate of... a lot of other tickets.

**Closed as not planned by krbz999** 2024-04-11 21:45 UTC
Labels: wontfix
